const state = { data: null, page: 'summary', spotQuery: '', roadQuery: '', geometryFilter: 'all' };
const content = document.getElementById('content'), modal = document.getElementById('modal'), modalBody = document.getElementById('modalBody');
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const spot = (id) => state.data.spots.find((s) => s.id === Number(id));
function toast(message) { const el = document.getElementById('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 3200); }
function openModal(eyebrow, title, html) { document.getElementById('modalEyebrow').textContent = eyebrow; document.getElementById('modalTitle').textContent = title; modalBody.innerHTML = html; modal.classList.remove('hidden'); }
function closeModal() { modal.classList.add('hidden'); modalBody.innerHTML = ''; }
document.querySelectorAll('[data-close]').forEach((el) => el.addEventListener('click', closeModal));
async function load(message) {
  state.data = await window.adminAPI.loadAdminData(); document.getElementById('loadState').textContent = `已加载 · ${new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}`; render();
  if (message) toast(message);
}
function render() { ({ summary: renderSummary, spots: renderSpots, roads: renderRoads, validation: renderValidation }[state.page])(); }
function renderSummary() {
  const d = state.data, v = d.validation;
  content.innerHTML = `<div class="stats">
    ${stat('地点总数', d.stats.spotCount, '当前可导航地点')}${stat('可用道路', d.stats.roadCount, '按无向道路统计')}${stat('道路几何', d.stats.roadGeometryCount, '已配置折线路径')}${stat('缺少几何', v.missingGeometry.length, '将使用直线降级')}
    ${stat('地图连通性', v.connected ? '正常' : '异常', `${v.visitedCount} / ${d.spots.length} 个地点可达`)}${stat('孤立地点', v.isolated.length, v.isolated.length ? '需要检查道路配置' : '未发现孤立点')}${stat('已关闭道路', d.stats.closedCount, '可在道路管理中恢复')}${stat('数据加载', '成功', '地点、道路与几何已同步')}
  </div><section class="panel"><div class="panel-head"><div><h3>数据健康状态</h3><p class="muted">基于当前数据实时检查</p></div><button class="soft" id="goValidation">查看完整检查</button></div><div class="validation-grid" style="margin-top:16px">${checkCard('图结构', v.connected, v.connected ? '当前地图完全连通。' : `有 ${v.unvisited.length} 个地点无法从首个地点访问。`)}${checkCard('道路几何', !v.missingGeometry.length && !v.invalidGeometry.length, v.missingGeometry.length ? `${v.missingGeometry.length} 条道路缺少几何。` : '所有可用道路均有有效几何。')}</div></section>`;
  document.getElementById('goValidation').onclick = () => switchPage('validation');
}
function stat(label, value, note) { return `<article class="stat"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`; }
function checkCard(title, good, text) { return `<article class="check-card"><header><h3>${title}</h3><span class="tag ${good ? 'good' : 'warn'}">${good ? '通过' : '需关注'}</span></header><p>${text}</p></article>`; }
function renderSpots() {
  const q = state.spotQuery.trim().toLowerCase(), rows = state.data.spots.filter((s) => !q || s.name.toLowerCase().includes(q) || String(s.id) === q);
  content.innerHTML = `<section class="panel" style="margin-top:0"><div class="toolbar"><input id="spotSearch" type="search" placeholder="按名称搜索或输入完整 ID" value="${escapeHtml(state.spotQuery)}"><span class="tag good">${rows.length} 个地点</span></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>名称</th><th>简介</th><th>x</th><th>y</th><th>操作</th></tr></thead><tbody>${rows.map((s) => `<tr><td>${s.id}</td><td><strong>${escapeHtml(s.name)}</strong></td><td class="description" title="${escapeHtml(s.description)}">${escapeHtml(s.description)}</td><td>${s.x}</td><td>${s.y}</td><td><div class="row-actions"><button data-edit-spot="${s.id}">查看 / 编辑</button></div></td></tr>`).join('')}</tbody></table>${rows.length ? '' : '<div class="empty">没有匹配的地点</div>'}</div></section>`;
  document.getElementById('spotSearch').oninput = (e) => { state.spotQuery = e.target.value; renderSpots(); document.getElementById('spotSearch').focus(); };
  document.querySelectorAll('[data-edit-spot]').forEach((b) => b.onclick = () => editSpot(Number(b.dataset.editSpot)));
}
function editSpot(id) {
  const s = spot(id); openModal('地点管理', `编辑 ${s.name}`, `<form id="spotForm" class="form-grid"><div class="field"><label>ID（不可修改）</label><input value="${s.id}" disabled></div><div class="field"><label>名称</label><input name="name" value="${escapeHtml(s.name)}" required></div><div class="field full"><label>地点介绍</label><textarea name="description" required>${escapeHtml(s.description)}</textarea></div><div class="field"><label>x 坐标</label><input name="x" type="number" min="0" step="any" value="${s.x}" required></div><div class="field"><label>y 坐标</label><input name="y" type="number" min="0" step="any" value="${s.y}" required></div><p class="form-note">保存坐标后不会自动修改道路几何。</p><div class="modal-actions"><button class="soft" type="button" data-cancel>取消</button><button class="primary" type="submit">保存修改</button></div></form>`);
  modalBody.querySelector('[data-cancel]').onclick = closeModal;
  document.getElementById('spotForm').onsubmit = async (e) => { e.preventDefault(); const f = new FormData(e.target); try { const result = await window.adminAPI.updateSpot({ id, name: f.get('name'), description: f.get('description'), x: f.get('x'), y: f.get('y'), originalX: s.x, originalY: s.y }); closeModal(); await load(result.coordinateChanged ? '地点坐标已更新。请确认相关道路几何是否仍与地图位置一致。' : '地点信息已更新。'); } catch (error) { toast(error.message); } };
}
function renderRoads() {
  const geometry = state.data.roadGeometry || {}, q = state.roadQuery.trim().toLowerCase();
  const rows = state.data.roads.filter((r) => { const key = r.from < r.to ? `${r.from}-${r.to}` : `${r.to}-${r.from}`, text = `${r.from} ${spot(r.from)?.name} ${r.to} ${spot(r.to)?.name}`.toLowerCase(); return (!q || text.includes(q)) && (state.geometryFilter !== 'missing' || !geometry[key]); });
  content.innerHTML = `<section class="panel" style="margin-top:0"><div class="toolbar"><input id="roadSearch" type="search" placeholder="按地点名称或 ID 搜索" value="${escapeHtml(state.roadQuery)}"><select id="geometryFilter"><option value="all">全部几何状态</option><option value="missing" ${state.geometryFilter === 'missing' ? 'selected' : ''}>仅缺少几何</option></select><button class="soft" id="geometryTool">打开几何采集工具</button><button class="primary" id="addRoad">增加道路</button></div><div class="table-wrap"><table><thead><tr><th>起点</th><th>终点</th><th>距离</th><th>道路几何</th><th>点数</th><th>操作</th></tr></thead><tbody>${rows.map((r) => roadRow(r, geometry)).join('')}</tbody></table>${rows.length ? '' : '<div class="empty">没有匹配的道路</div>'}</div></section>${closedPanel()}`;
  document.getElementById('roadSearch').oninput = (e) => { state.roadQuery = e.target.value; renderRoads(); document.getElementById('roadSearch').focus(); }; document.getElementById('geometryFilter').onchange = (e) => { state.geometryFilter = e.target.value; renderRoads(); };
  document.getElementById('geometryTool').onclick = () => window.adminAPI.openGeometryTool(); document.getElementById('addRoad').onclick = addRoadModal;
  document.querySelectorAll('[data-edit-road]').forEach((b) => b.onclick = () => roadDistanceModal(Number(b.dataset.from), Number(b.dataset.to)));
  document.querySelectorAll('[data-close-road]').forEach((b) => b.onclick = () => confirmClose(Number(b.dataset.from), Number(b.dataset.to)));
  document.querySelectorAll('[data-restore-road]').forEach((b) => b.onclick = async () => { try { await window.adminAPI.restoreRoad({ from: Number(b.dataset.from), to: Number(b.dataset.to) }); await load('道路已恢复，原有几何将继续复用。'); } catch (e) { toast(e.message); } });
}
function roadRow(r, geometry) { const key = r.from < r.to ? `${r.from}-${r.to}` : `${r.to}-${r.from}`, points = geometry[key]; return `<tr><td>${r.from} · ${escapeHtml(spot(r.from)?.name || '未知')}</td><td>${r.to} · ${escapeHtml(spot(r.to)?.name || '未知')}</td><td>${r.distance} 米</td><td><span class="tag ${points ? 'good' : 'warn'}">${points ? '已配置' : '缺少几何'}</span></td><td>${points?.length || 0}</td><td><div class="row-actions"><button data-edit-road data-from="${r.from}" data-to="${r.to}">修改距离</button><button data-close-road data-from="${r.from}" data-to="${r.to}">临时关闭</button></div></td></tr>`; }
function closedPanel() { const list = state.data.closedRoads; return `<section class="panel"><div class="panel-head"><h3>已关闭道路</h3><span class="tag ${list.length ? 'warn' : 'good'}">${list.length} 条</span></div>${list.length ? `<div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>起点</th><th>终点</th><th>原距离</th><th>关闭时间</th><th>操作</th></tr></thead><tbody>${list.map((r) => `<tr><td>${r.from} · ${escapeHtml(spot(r.from)?.name)}</td><td>${r.to} · ${escapeHtml(spot(r.to)?.name)}</td><td>${r.distance} 米</td><td>${new Date(r.closedAt).toLocaleString('zh-CN')}</td><td><div class="row-actions"><button data-restore-road data-from="${r.from}" data-to="${r.to}">恢复道路</button></div></td></tr>`).join('')}</tbody></table></div>` : '<p class="empty">当前没有临时关闭的道路</p>'}</section>`; }
function roadFields(distance = '') { return `<div class="field"><label>起点</label><select name="from" required><option value="">请选择</option>${state.data.spots.map((s) => `<option value="${s.id}">${s.id} · ${escapeHtml(s.name)}</option>`).join('')}</select></div><div class="field"><label>终点</label><select name="to" required><option value="">请选择</option>${state.data.spots.map((s) => `<option value="${s.id}">${s.id} · ${escapeHtml(s.name)}</option>`).join('')}</select></div><div class="field full"><label>道路距离（米）</label><input name="distance" type="number" min="0.01" step="any" value="${distance}" required></div>`; }
function addRoadModal() { openModal('道路管理', '增加道路', `<form id="roadForm" class="form-grid">${roadFields()}<p class="form-note">新增道路不会自动生成复杂几何路径。</p><div class="modal-actions"><button class="soft" type="button" data-cancel>取消</button><button class="primary" type="submit">添加道路</button></div></form>`); modalBody.querySelector('[data-cancel]').onclick = closeModal; document.getElementById('roadForm').onsubmit = async (e) => { e.preventDefault(); const f = new FormData(e.target); try { const result = await window.adminAPI.addRoad(Object.fromEntries(f)); closeModal(); await load(result.missingGeometry ? '道路已添加，但尚未配置地图几何路径。用户端暂时会使用直线降级显示，建议补充 road_geometry.json。' : '道路已添加。'); } catch (error) { toast(error.message); } }; }
function roadDistanceModal(from, to) { const road = state.data.roads.find((r) => (r.from === from && r.to === to) || (r.from === to && r.to === from)); openModal('道路管理', '修改道路距离', `<form id="distanceForm" class="form-grid"><div class="field full"><label>道路</label><input value="${from} · ${escapeHtml(spot(from).name)} ↔ ${to} · ${escapeHtml(spot(to).name)}" disabled></div><div class="field full"><label>距离（米）</label><input name="distance" type="number" min="0.01" step="any" value="${road.distance}" required></div><div class="modal-actions"><button class="soft" type="button" data-cancel>取消</button><button class="primary" type="submit">保存距离</button></div></form>`); modalBody.querySelector('[data-cancel]').onclick = closeModal; document.getElementById('distanceForm').onsubmit = async (e) => { e.preventDefault(); try { await window.adminAPI.updateRoad({ from, to, distance: new FormData(e.target).get('distance') }); closeModal(); await load('道路距离已更新。'); } catch (error) { toast(error.message); } }; }
function confirmClose(from, to) { openModal('危险操作确认', '临时关闭道路', `<p>关闭后，该道路会从用户端路径计算中移除，但原有几何数据会保留。</p><p><strong>${escapeHtml(spot(from).name)} ↔ ${escapeHtml(spot(to).name)}</strong></p><div class="modal-actions"><button class="soft" data-cancel>取消</button><button class="danger" id="confirmClose">确认临时关闭</button></div>`); modalBody.querySelector('[data-cancel]').onclick = closeModal; document.getElementById('confirmClose').onclick = async () => { try { await window.adminAPI.closeRoad({ from, to }); closeModal(); await load('道路已临时关闭，用户端重新进入后将使用最新道路数据。'); } catch (e) { toast(e.message); } }; }
function list(items, mapper = (x) => x) { return items.length ? `<ul>${items.slice(0, 30).map((x) => `<li>${escapeHtml(mapper(x))}</li>`).join('')}</ul>` : '<p>未发现问题。</p>'; }
function renderValidation() { const v = state.data.validation; content.innerHTML = `<div class="validation-grid">${validationCard('连通性检查', v.connected, `${v.visitedCount} / ${state.data.spots.length} 个地点已访问`, list(v.unvisited, (s) => `${s.id} · ${s.name}`))}${validationCard('孤立地点', !v.isolated.length, `${v.isolated.length} 个`, list(v.isolated, (s) => `${s.id} · ${s.name}`))}${validationCard('无效与重复道路', !v.invalidRoads.length && !v.duplicates.length, `${v.invalidRoads.length + v.duplicates.length} 项`, list([...v.invalidRoads.map((r) => `第 ${r.line} 行：${r.reason}`), ...v.duplicates.map((r) => `重复道路 ${r.key}`)]))}${validationCard('道路几何完整性', !v.missingGeometry.length && !v.extraGeometry.length && !v.invalidGeometry.length, `${v.missingGeometry.length} 缺失 / ${v.extraGeometry.length} 多余 / ${v.invalidGeometry.length} 无效`, list([...v.missingGeometry.map((k) => `缺少几何：${k}`), ...v.extraGeometry.map((k) => `多余几何：${k}`), ...v.invalidGeometry.map((k) => `无效几何：${k}`)]))}${validationCard('地点坐标', !v.invalidCoordinates.length && !v.duplicateCoordinates.length && !v.outOfBounds.length, v.mapBounds ? `地图尺寸 ${v.mapBounds.width} × ${v.mapBounds.height}` : '无法读取地图尺寸', list([...v.invalidCoordinates.map((s) => `非法坐标：${s.id} · ${s.name}`), ...v.duplicateCoordinates.map((x) => `重复坐标 ${x.coordinate}：${x.spots.map((s) => s.name).join('、')}`), ...v.outOfBounds.map((s) => `超出地图：${s.id} · ${s.name} (${s.x}, ${s.y})`)]))}</div>`; }
function validationCard(title, good, detail, body) { return `<article class="check-card panel" style="margin:0"><header><h3>${title}</h3><span class="tag ${good ? 'good' : 'bad'}">${good ? '通过' : '发现问题'}</span></header><p>${detail}</p>${body}</article>`; }
function switchPage(page) { state.page = page; document.querySelectorAll('nav button').forEach((b) => b.classList.toggle('active', b.dataset.page === page)); const titles = { summary: ['数据概况', '校园地图运行概览'], spots: ['地点管理', '查看和维护地点信息'], roads: ['道路管理', '维护可用道路与关闭状态'], validation: ['数据检查', '地图完整性检查'] }; document.getElementById('pageEyebrow').textContent = titles[page][0]; document.getElementById('pageTitle').textContent = titles[page][1]; render(); }
document.querySelectorAll('nav button').forEach((b) => b.onclick = () => switchPage(b.dataset.page)); document.getElementById('refreshButton').onclick = () => load('数据已刷新。'); document.getElementById('previewButton').onclick = () => window.campusAPI.navigate('user'); document.getElementById('logoutButton').onclick = async () => { await window.adminAPI.logout(); await window.campusAPI.navigate('entry'); };
(async () => { if (!await window.adminAPI.hasSession()) { await window.campusAPI.navigate('entry'); return; } await load(); })().catch((error) => { document.getElementById('loadState').textContent = '加载失败'; content.innerHTML = `<section class="panel"><h3>数据加载失败</h3><p>${escapeHtml(error.message)}</p></section>`; });
